name: audio_call
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_bloc: 8.1.2
  flutter_voximplant: 3.8.0
  flutter_callkit_voximplant: 2.1.0
  uuid: 3.0.7
  flutter_local_notifications: 13.0.0
  permission_handler: 10.2.0
  shared_preferences: 2.0.18
  equatable: 2.0.5
  firebase_core: 2.8.0
  firebase_messaging: 14.3.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

